name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # Atualiza automaticamente a cada 6 horas
  workflow_dispatch:  # Rode manualmente

permissions:
  contents: write  # Permissão essencial pra criar branches

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      - name: Deploy to output branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output  # Cria/atualiza a branch output
          folder: dist    # Pasta com os SVGs
          clean: true     # Limpa arquivos antigos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
